FROM python:3.12

RUN  mkdir /app
COPY requirements.txt /app

RUN pip install -r /app/requirements.txt

COPY . /app

WORKDIR /app

CMD python ocpp16_201.py --service_port 16000 --upstream ws://ocpp:9000/ocpp --redis_host redis --redis_port 6379 --redis_db 7

